apiVersion: skaffold/v2alpha3
Kind: Config
deploy:
   Kubectl:
      manifest:
         - ./infra/k8s/*
build:
   local:
      push: false
   artifacts:
      - image: shadman/auth
        context: auth
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: 'src/**/*.ts'
                dest: .
