apiVersion: skaffold/v2alpha3
kind: Config
deploy:
   kubectl:
      manifests:
         - ./infra/k8s/*
build:
   local:
      push: false
   artifacts:
      - image: shadman/auth
        context: auth
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: 'src/**/*.ts'
                dest: .
      - image: shadman/client
        context: client
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '**/*.js'
                dest: .
      - image: shadman/tickets
        context: tickets
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: 'src/**/*.ts'
                dest: .
      - image: shadman/orders
        context: orders
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: 'src/**/*.ts'
                dest: .
      - image: shadman/expiration
        context: expiration
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: 'src/**/*.ts'
                dest: .
      - image: shadman/payments
        context: payments
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: 'src/**/*.ts'
                dest: .
